# Generated by Django 3.1.3 on 2021-01-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20210131_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='date_beginning',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
