# Generated by Django 3.1.3 on 2021-01-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytree',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
